Issue 21: Use cBioPortal downloadable data rather than API
cancervariants/evidence-normalization pull request #25
Opened 2022-03-28 16:47 UTC by korikuzma

closes #21

2022-03-29 14:46 UTC, korikuzma commented
Not focusing on gnomAD because of this comment: https://github.com/cancervariants/evidence-normalization/issues/21#issuecomment-1081962242

2022-03-29 14:54 UTC, jsstevenson requested changes
Might be helpful to retain a little bit more information if downloads fail but looks good otherwise

2022-03-29 14:54 UTC, jsstevenson commented on evidence/dev/etl/cancer_hotspots.py
> +                    f.write(r.content)
log the code if it isn't 200?

2022-03-29 14:54 UTC, jsstevenson commented on evidence/dev/etl/cbioportal.py
> +        if response.status_code == 200:
also log code if fails

2022-03-30 15:24 UTC, jsstevenson approved these changes

2022-03-30 15:25 UTC, merged